#!/usr/bin/python3
import sys
import time

def facto(number):
    '''Takes an input number.
    Args: number: input integer.
    Return: returns to factors.
'''
    factors = []
    for i in range(2, number // 2 + 1):
        if number % i == 0:
            factors.append((i, number // i))
            break
    return factors

def main(input_file):
    with open(input_file, 'r') as file:
        for line in file:
            number = int(line.strip())
            start_time = time.time()
            factors = facto(number)
            end_time = time.time()
            if factors:
                p, q = factors[0]
                print(f"{number}={p}*{q}")
                print(f"Execution Time: {end_time -start_time:.6f} seconds")

if __name__ == "__main__":
    '''Reads the input file.
    '''
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)

    input_file = sys.argv[1]
    main(input_file)
